#!/bin/bash

echo "🚀 HƯỚNG DẪN DEPLOY LÊN GITHUB"
echo "=============================="
echo ""
echo "1. Tạo repository mới trên GitHub.com:"
echo "   - Đi tới https://github.com"
echo "   - Click '+' → 'New repository'"
echo "   - Tên repository: lumi-lighting"
echo "   - KHÔNG tick 'Add a README file'"
echo "   - Click 'Create repository'"
echo ""
echo "2. Copy URL của repository (ví dụ: https://github.com/username/lumi-lighting.git)"
echo ""
echo "3. Chạy các lệnh sau (thay YOUR_GITHUB_URL bằng URL thực tế):"
echo ""
echo "git remote add origin YOUR_GITHUB_URL"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "VÍ DỤ:"
echo "git remote add origin https://github.com/nghinguyen/lumi-lighting.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "✅ Sau khi hoàn thành, dự án sẽ có trên GitHub!" 